spring.jpa.show-sql=false
spring.jpa.open-in-view=false

server.forward-headers-strategy=framework

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
